name: "Check if image persists in registry"
description: "Check if image persists in registry"

inputs:
  image:
    required: true
    type: string
  tag:
    required: false
    type: string
  arch:
    required: false
    type: string
    default: "linux/amd64"

outputs:
  exists:
    value: ${{ steps.check_image.outputs.exists }}

runs:
  using: "composite"
  steps:
    - id: check_image
      run: |
        if docker manifest inspect ${{ inputs.image }} | jq '.manifests[].platform | [.os, .architecture] | join("/")' | grep -qi "${{ inputs.arch }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
        else
            echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
