name: Build and Push Multi-arch Docker Image

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
      tags:
        required: false
        type: string
        default: ''
      latest:
        required: false
        type: boolean
        default: false
      platforms:
        required: false
        type: string
        default: |
          linux/amd64
      build_args:
        required: false
        type: string
        default: ''
      context:
        required: false
        type: string
        default: '.'
      docker_file:
        required: false
        type: string
        default: 'Dockerfile'
      setup_qemu:
        required: false
        type: boolean
        default: false
      runs_on:
        required: false
        type: string
        default: '["ubuntu-latest"]'
      sha_tag:
        required: false
        type: boolean
        default: true
      push:
        required: false
        type: boolean
        default: true
      cache_from:
        required: false
        type: string
        default: ""
      cache_to:
        required: false
        type: string
        default: ""

    secrets:
      read_repo_token:
        required: false
      gcp_service_account_key:
        required: false
      docker_registy_login:
        required: false
      docker_registy_password:
        required: false

jobs:
  build-and-push:
    runs-on: ${{ fromJson(inputs.runs_on) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.read_repo_token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      if: ${{ inputs.setup_qemu }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set git sha tag for docker image
      id: sha_tag
      run: |
        cd ${{ inputs.context }}
        echo "value=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      if: ${{ inputs.sha_tag }}

    - name: Set cache values
      id: cache
      run: |
        CACHE_FROM="${{ inputs.cache_from }}"
        CACHE_TO="${{ inputs.cache_to }}"

        if [ -z "$CACHE_FROM" ]; then
          CACHE_FROM="type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:cache"
        fi

        if [ -z "$CACHE_TO" ]; then
          CACHE_TO="type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:cache,mode=max"
        fi

        echo "from=$CACHE_FROM" >> $GITHUB_OUTPUT
        echo "to=$CACHE_TO" >> $GITHUB_OUTPUT

    - name: Login to registry
      uses: pubky/ci-workflows/.github/actions/docker/registry_login@main
      with:
        registry: ${{ inputs.registry }}
        gcp_service_account_key: ${{ secrets.gcp_service_account_key }}

    - name: Set image tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=raw,value=latest,enable=${{ inputs.latest }}
          type=raw,value=${{ steps.sha_tag.outputs.value }},enable=${{ inputs.sha_tag }}
          ${{ inputs.tags }}

    - name: Build and push image
      id: build
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        context: ${{ github.workspace }}/${{ inputs.context }}
        file: ${{ github.workspace }}/${{ inputs.context }}/${{ inputs.docker_file }}
        tags: ${{ steps.meta.outputs.tags }}
        build-args: ${{ inputs.build_args }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: ${{ steps.cache.outputs.from }}
        cache-to: ${{ steps.cache.outputs.to }}
